### ISSUE TITLE
type-related terminology is confusing, perplexing, misleading, disconcerting, disorienting

### ISSUE THREAD

**Issue by njsmith** [hawkowl/towncrier#72]
The config file has a concept of different types of fixes, they're configured through a section called `type`. OK.

The code calls them categories everywhere. O...kay? I know type collides with the python builtin but switching to distinguishing between sections and categories? That's way worse. Though at least only people reading the code run into this.

And then the way you configure the file name used for a type/category is by the key `directory`, which does not specify a directory at all. C'MON.

(Maybe `tag` or `slug` or something?)

**Comment by hawkowl** [comment]
🤣 yes this is correct

**Comment by adiroiban** [comment]
Or use `file extension` as this is looking for the extension of the file :)

**Comment by njsmith** [comment]
@adiroiban: but see #62 and #65.

**Comment by adiroiban** [comment]
Thanks for the links. Good work with the extension. 

`tag` for me means that you can have multiple tags to a single fragment.
`slug` is something identifying that particular fragment.

Maybe just go with `category`.

There are many things that are confusing (start_string vs start_line)

I think that is ok if we accumulate more of these issues and do a change in towncrier v1

-----------

Here is a suggestion

```
[tool.towncrier]
    package = "super.duper"
    package_dir = "/"

    template = "release-notes/template.j2"
    fragments = "release-notes/"
    destination = "super/duper/static/documentation/release-notes.rst"

    start_marker = ".. release-notes-start\n"

    title_format  = "Version {version}, {project_date}"
    issue_format = "[#{issue}]"

    [[tool.towncrier.category]]
        name = "feature"
        title = "New Features"
        show_content = true
```

**Comment by adiroiban** [comment]
Just an update.
We now have something like this

The `directory` part is very confusing  ... as you usually have `sections` for separate directories

```toml
[tool.towncrier]
[[tool.towncrier.type]]
directory = "deprecation"
name = "Deprecations"
showcontent = true

[[tool.towncrier.type]]
directory = "chore"
name = "Other Tasks"
showcontent = false

[[tool.towncrier.type]]
directory = "deps"
name = "Dependency Changes"
showcontent = true
check = false
```

Happy to receive suggestions on how to improve this.
